# Generated by Django 2.2.2 on 2019-07-20 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('dateandtime', models.DateTimeField(default=datetime.datetime(2019, 7, 20, 8, 1, 37, 660937))),
            ],
        ),
    ]
