# Generated by Django 2.2.2 on 2019-07-06 07:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('dob', models.DateTimeField(default=datetime.datetime(2019, 7, 6, 7, 16, 31, 911346))),
            ],
        ),
        migrations.CreateModel(
            name='Employee1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Emp Name', max_length=20)),
                ('salary', models.FloatField(default=10000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Company')),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
