# Generated by Django 2.2.2 on 2019-07-06 08:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190706_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 6, 8, 6, 2, 75592)),
        ),
    ]
