# Generated by Django 2.2.2 on 2019-07-07 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20190706_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('founder', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 7, 7, 11, 10, 420409)),
        ),
        migrations.AddField(
            model_name='employee1',
            name='language',
            field=models.ManyToManyField(to='myapp.Language'),
        ),
    ]
