# Generated by Django 2.2.2 on 2019-07-11 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190707_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='dob',
        ),
        migrations.AddField(
            model_name='company',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 10, 43, 59, 738121)),
        ),
    ]
