# Generated by Django 2.2.2 on 2019-07-11 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20190711_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 10, 47, 26, 559126)),
        ),
    ]
