# Generated by Django 2.2.2 on 2019-07-11 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20190711_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='date',
        ),
        migrations.AddField(
            model_name='company',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 10, 49, 4, 465603)),
        ),
    ]
