# Generated by Django 2.2.2 on 2019-07-20 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20190713_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 20, 7, 59, 29, 536702)),
        ),
    ]
