# Generated by Django 2.2.2 on 2019-07-20 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20190720_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 20, 8, 1, 37, 653966)),
        ),
    ]
