# Generated by Django 2.2.2 on 2019-07-28 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20190720_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='c_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 28, 7, 16, 9, 323933)),
        ),
    ]
